#!/usr/bin/env bash
# edits nginx default server conf to redirect a particular uri
sed -i '/location \//i \
		location /redirect_me {\
			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
		}\n' /etc/nginx/conf.d/default.conf
nginx -s reload
