#!/usr/bin/env bash
# install and configure haproxy as load balancer for my two servers
if [ ! "$(which haproxy)" ]; then
    sudo apt-get -y install --no-install-recommends software-properties-common
    add-apt-repository ppa:vbernat/haproxy-2.7
    apt update && apt upgrade -y
    apt install -y haproxy=2.8.\*
fi

if [ ! -d /etc/haproxy ]; then
    mkdir /etc/haproxy
fi
cat <<-EOF > /etc/haproxy/haproxy.cfg
defaults
    timeout connect 3600
    timeout server 360000
    timeout client 360000

frontend loadin
    bind *:80
    mode http
    default_backend loadbalance

backend loadbalance
    mode http
    server 394869-web-01 18.234.253.13:80
    server 394869-web-02 100.25.15.253:80
EOF

test -f /etc/haproxy/haproxy.cfg || exit 1
haproxy -c -f /etc/haproxy.haproxy.cfg
