#!/usr/bin/env bash
# install and configure haproxy as load balancer for my two servers
if [ ! "$(which haproxy)" ]; then
    sudo apt-get -y install --no-install-recommends software-properties-common
    add-apt-repository ppa:vbernat/haproxy-2.8
    apt update && apt upgrade -y
    apt install -y haproxy=2.8.\*
fi

if [ ! -d /etc/haproxy ]; then
    mkdir /etc/haproxy
fi
cat <<-EOF > /etc/haproxy/haproxy.cfg
defaults
    mode http
    timeout connect 10s
    timeout server 20s
    timeout client 15s

frontend loadin
    bind *:80
    default_backend loadbalance

backend loadbalance
    balance roundrobin
    server 394869-web-01 18.234.253.13:80 check
    server 394869-web-02 100.25.15.253:80 check
EOF

service haproxy start
