#!/usr/bin/env bash
# script makes sure nginx is listening to prot 80
proc_port_80=$(netstat -lpn | grep -m 1 "[ :]80 " | awk "{print $7}")
if [[ -n $proc_port_80 ]]; then
    proc_id=$(cut -d/ -f1)
    kill -9 "$proc_id"
fi
sed -i -r 's/(listen.*[ :])[0-9]+(;| .*;$)/\180\2/g' /etc/nginx/sites-enabled/default
service nginx restart
