#!/usr/bin/env bash
# Manages the manage my process script

args=("start" "stop" "restart")
pidbg=0
if [[ $# -lt 1 || ! ${args[*]} =~ $1 ]];then
	echo "Usage: manage_my_process {start|stop|restart} "
fi

function start_cmds(){
	./manage_my_process &
	pidbg=$!
	echo $pidbg >> /var/run/my_process.pid
}
function stop_cmds(){
	pkill -9 -f manage_my_process
	sudo rm /var/run/my_process.pid
}
if [[ $1 == "start" ]]; then
	start_cmds
	echo "manage_my_process started"
elif [[ $1 == "stop" ]];then
	stop_cmds
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]];then
	stop_cmds
	start_cmds
	echo "manage_my_process restarted"
fi
