#!/usr/bin/env bash
# Prints a word from n times and with conditions
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "Bad luck"
	elif [ $i -eq 7 ]; then
		echo "Good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
