#!/usr/bin/env bash
# loops using while and case statements
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
		4)
			echo "bad luck in china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
			;;
	esac
	(( i++ ))
done
