#!/usr/bin/env bash
# loops using while and case statements
i=1
while [ $i -lt 21 ]; do
	echo $i
	case $i in
		4)
			echo "bad luck in China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
done
