#!/usr/bin/env bash
# changes the ip addresses for localhost and facebook.com
cat /etc/hosts > ~/hosts.new
sed -i 's/^127.*1/127.0.0.2/' ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
