#!/usr/bin/env bash
# creates user for nginx process and run nginx woth that
if ! id nginx &>/dev/null
then
	useradd -m nginx
fi
if ! nginx -v
then
	apt-get update -y
	apt-get install nginx -y
fi
sed -i -r "s/^user .+/user nginx;/g" /etc/nginx/nginx.conf
cat <<EOF > /etc/nginx/conf.d/default.conf
server {
	listen 8080 default_server;
	listen [::]:8080 default_server;

	root /usr/share/nginx/html/;

	location / {
		index index.html index.htm;
	}
}
EOF
if ! service nginx status &>/dev/null
then
	nginx
else
	nginx -s reload;
fi
